# Generated by Django 3.1.2 on 2020-10-11 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cerveza', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('C', 'En curso'), ('F', 'Finalizado')], max_length=1)),
                ('costo_total', models.IntegerField()),
                ('cantidad_botellas', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(null=True)),
                ('cerveza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerveza.cervezamodel')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cliente', to=settings.AUTH_USER_MODEL)),
                ('fabricante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_fabricante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
