# Generated by Django 3.1.2 on 2020-10-11 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerveza', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosmodel',
            name='cerveza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='cerveza.cervezamodel'),
        ),
    ]
