# Generated by Django 3.1.2 on 2020-12-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CervezaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('color', models.CharField(choices=[('M', 'Rubia'), ('N', 'Negra'), ('A', 'Ambar'), ('R', 'Roja')], max_length=1)),
                ('alcohol', models.FloatField()),
                ('fermentacion', models.CharField(choices=[('A', 'Ale'), ('L', 'Larger'), ('H', 'Hibrida')], max_length=1)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
