# Generated by Django 3.1.2 on 2020-12-06 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cerveza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cervezamodel',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cervezas', to=settings.AUTH_USER_MODEL),
        ),
    ]
